---
- name: Server deploy
  ansible.builtin.import_playbook:
    - playbooks/task-add-locale-en-US.yaml
    - playbooks/playbook-ipsec-server-custom.yaml
    - playbooks/playbook-zabbix-server-v70-part-1.yaml
    - playbooks/playbook-zabbix-server-v70-part-2.yaml
    - playbooks/task-add-grafana.yaml
    - playbooks/task-add-certbot.yaml

