---
- name: Ipsec-agent-install
  ansible.builtin.import_playbook: 
    - playbooks/playbook-ipsec-agent-custom.yaml
- name: Zabbix-agent-install
  ansible.builtin.import_playbook: 
    - playbooks/playbook-zabbix-agent-custom-v70.yaml
    - playbooks/task-add-iperf3.yaml
    - playbooks/task-client-srv.yaml
