- hosts: localhost
  become: yes
  vars:
    client_list: [172.16.16.2, 172.16.16.4, 172.16.16.5, 172.16.16.6, 172.16.16.7, 172.16.16.8, 172.16.16.9, 172.16.16.10, 172.16.16.11]          
    test_bandwidth: 70M
    test_duration: 600
    async_timeout: 700
  tasks:
    - name: Одновременный запуск тестов
      command: >
        iperf3 -c {{ item }} -t {{ test_duration }} -i 10 -R -u -b {{ test_bandwidth }}
      with_items: "{{ client_list }}"
      async: "{{ async_timeout }}"
      poll: 0
      register: test_results
      ignore_errors: true

    - name: Awayt iperf3 processes
      async_status:
        jid: "{{ item.ansible_job_id }}"
      register: job_status
      until: job_status.finished
      retries: 5
      delay: 125
      with_items: "{{ test_results.results }}"
      when: item.finished == 0
      ignore_errors: true

    - name: Save results to file
      copy:
        content: >
          {{
            job_status.results
            | selectattr('finished', 'equalto', 1)
            | map(attribute='stdout')
            | reject('equalto', None)
            | join('\n')
          }}
        dest: /root/iperf_results2.log
      become: true
      become_user: root
