aiodns==3.2.0
aiohappyeyeballs==2.4.4
aiohttp==3.10.5
aiosignal==1.3.2
ansible==9.11.0
ansible-bender==0.10.1
ansible-builder==3.1.0
ansible-collections-openstack.cloud==2.2.0
ansible-compat==24.9.1
ansible-core==2.16.12
ansible-creator==24.11.0
ansible-lint==24.9.2
ansibug==0.2.0
argcomplete==3.5.2
attrs==24.2.0
babel==2.16.0
bcrypt==4.1.2
Beaker==1.12.1
beautifulsoup4==4.12.3
bindep==2.11.0
black==24.10.0
blinker==1.9.0
blivet==3.11.0
blivet-gui==2.6.0
bracex==2.5.post1
Brlapi==0.8.5
Brotli==1.1.0
capstone==5.0.1
certifi==2023.5.7
cffi==1.17.0
charset-normalizer==3.3.2
click==8.1.7
click-plugins==1.1.1
cockpit @ file:///builddir/build/BUILD/cockpit-331-build/cockpit-331/tmp/wheel/cockpit-331-py3-none-any.whl#sha256=06bb2599b2d77daa0a4ddcb38ada485e73f749313c8d51a5744a72e7cb1947fe
colored-traceback==0.3.0
copr==2.0
copr-cli==2.0
crypt_r==3.13.1
cryptography==43.0.0
cupshelpers==1.0
daemonize==2.5.0
dasbus==1.7
dbus-python==1.3.2
decorator==5.1.1
defusedxml==0.7.1
Deprecated==1.2.15
distro==1.9.0
dnf==4.22.0
dnspython==2.6.1
dogpile.cache==1.3.1
execnet==2.1.1
fedora-third-party==0.10
file-magic==0.4.0
filelock==3.16.1
Flask==3.1.0
fros==1.1
frozenlist==1.5.0
gssapi==1.7.3
humanize==4.9.0
idna==3.7
ifaddr==0.1.7
importlib_metadata==8.5.0
iniconfig==1.1.1
iniparse==0.5
intervaltree==3.1.0
ipaclient==4.12.2
ipalib==4.12.2
ipaplatform==4.12.2
ipapython==4.12.2
ipaserver==4.12.2
iso639==0.1.4
iso8601==1.1.0
itsdangerous==2.2.0
Jinja2==3.1.4
jmespath==1.0.1
jsonpatch==1.33
jsonpointer==2.4
jsonschema==4.19.1
jsonschema-specifications==2023.11.2
jwcrypto==1.4.2
kdcproxy==1.0.0
keystoneauth1==5.6.0
koji==1.35.1
langtable==0.0.68
lib389==3.1.1
libcomps==0.1.21
libdnf==0.73.4
libdnf5==5.2.8.1
libvirt-python==10.6.0
load-dotenv==0.1.0
louis==3.28.0
lxml==5.2.1
Mako==1.2.3
markdown-it-py==3.0.0
MarkupSafe==2.1.5
mdurl==0.1.2
mercurial==6.8.2
multidict==6.0.5
munch==2.5.0
mutagen==1.47.0
mypy-extensions==1.0.0
netaddr==1.3.0
netifaces==0.11.0
nftables==0.1
numpy==1.26.4
olefile==0.47
omsdk==1.2.513
openrazer==3.9.0
openrazer_daemon==3.9.0
openstacksdk==3.0.0
os-service-types==1.7.0
osbuild==136
packaging==24.1
paramiko==3.5.0
Parsley==1.3
Paste==3.10.1
pathspec==0.12.1
pbr==5.11.1
pcp==5.0
pcs==0.11.8
perf==0.1
pexpect==4.9.0
pid==2.2.3
pillow==11.0.0
platformdirs==4.2.2
pluggy==1.5.0
plumbum==1.7.2
ply==3.11
productmd==1.41
progress==1.6
progressbar2==3.53.2
psutil==5.9.8
ptyprocess==0.7.0
pwntools==4.13.1
pwquality==1.4.5
pyasn1==0.6.0
pyasn1_modules==0.4.0
pycairo==1.25.1
pycares==4.3.0
pycparser==2.20
pycrypto==2.6.1
pycryptodomex==3.21.0
pycups==2.0.4
pycurl==7.45.3
pyelftools==0.31
pyenchant==3.2.2
pygdbmi==0.11.0.0
pygit2==1.16.0
Pygments==2.18.0
PyGObject==3.48.2
pyinotify==0.9.6
pykickstart==3.58
PyNaCl==1.5.0
pyOpenSSL==24.2.1
pyparsing==3.1.2
pyparted==3.13.0
pyserial==3.5
pysmi==0.3.4
pysnmp==4.4.12
pysnmp-mibs==0.1.6
PySocks==1.7.1
pyspnego==0.11.1
pytest==8.3.4
pytest-mock==3.14.0
pytest-xdist==3.6.1
python-augeas==1.1.0
python-dateutil==2.8.2
python-dotenv==1.0.1
python-ldap==3.4.4
python-linux-procfs==0.7.3
python-meh==0.52
python-pam==2.0.2
python-utils==3.7.0
python-yubico==1.3.3
pyudev==0.24.3
pyusb==1.2.1
pywinrm==0.4.3
pyxdg==0.27
PyYAML==6.0.1
qrcode==7.4.2
referencing==0.35.1
regex==2024.9.11
requests==2.32.3
requests-file==2.0.0
requests-ftp==0.3.1
requests-gssapi==1.2.3
requests-toolbelt==1.0.0
requests_ntlm==1.2.0
requestsexceptions==1.4.0
resolvelib==1.0.1
rich==13.9.4
ROPGadget==7.4
rpds-py==0.19.1
rpm==4.20.0
rpmautospec==0.7.3
rpmautospec-core==0.1.5
rpyc==6.0.1
ruamel.yaml==0.18.6
ruamel.yaml.clib==0.2.12
selinux @ file:///builddir/build/BUILD/libselinux-3.7-build/libselinux-3.7/src
sentry-sdk==2.17.0
sepolicy @ file:///builddir/build/BUILD/policycoreutils-3.7-build/selinux-3.7/python/sepolicy
setools==4.5.1
setproctitle==1.3.3
setroubleshoot @ file:///builddir/build/BUILD/setroubleshoot-3.3.35-build/setroubleshoot-3.3.35/src
setuptools==69.2.0
simpleaudio==1.0.4
simpleline==1.9.0
six==1.16.0
sortedcontainers==2.4.0
sos==4.8.2
soupsieve==2.6
SSSDConfig==2.10.0
stevedore==5.2.0
subprocess-tee==0.4.2
subscription-manager==1.30.2
systemd-python==235
tabulate==0.9.0
Tempita==0.5.2
tomli==2.0.1
tornado==6.3.3
typing_extensions==4.12.2
unicorn==2.0.1.post1
unix_ar==0.2.1
urllib3==1.26.20
wcmatch==10.0
wcwidth==0.2.13
websockets==12.0
Werkzeug==3.1.3
wrapt==1.17.0
xkbregistry==0.3
xmltodict==0.13.0
yamllint==1.35.1
yarl==1.9.4
yt-dlp==2024.9.27
zipp==3.21.0
zstandard==0.23.0