all:
  hosts:
    zabbix-servers:
      ansible_host: 146.0.80.152
      ansible_port: 22
      ansible_user: gnet
      ansible_become_password: Frdfkfyu2023!
    zabbix-agents:
      - name: zabbix-agent-petro
        ansible_host: 193.201.217.126 
        ansible_port: 7422
        ansible_user: user
        ansible_become_password: 000200!
      - name: zabbix-agent-gnet  
        ansible_host: mbit-de-gw.mbit-consultants.com
        ansible_port: 22
        ansible_user: gnet 
        ansible_become_password: Frdfkfyu2023!

      - name: zabbix-agent-vm
        ansible_host: 192.168.100.99/24
        ansible_port: 22
        ansible_user: gnet
    mikrotik:
      - name: ax.lan
        ansible_host: 10.10.100.1
        ansible_port: 22
      - name: ax.lan
        ansible_host: 10.10.100.2
        ansible_user: gnet
        ansible_password: codeX195
    test_server:
      - name: vpn
        ansible_host: localhost
        


      
        