---
- hosts: zabbix_agents
  vars_files:
    - ./../zabbix-agent.ini
  become: true
  tasks:
    - name: Install iperf3
      apt:
        name: iperf3
        state: present
        update_cache: yes

    - name: Ping the iperf3 server
      ping:
        data: "Checking server connectivity"
      register: ping_result

    - name: Fail if server is not reachable
      fail:
        msg: "iperf3 server is not reachable!"
      when: ping_result.failed


    - name: Run iperf3 traffic test
      command: iperf3 -c {{ iperf_server_ip }} -n 100M
      register: iperf_result
      become: true


    - name: Display iperf3 results
      debug:
        msg: "{{ iperf_result.stdout }}"
