FROM debian:12

RUN apt-get update && apt-get install -y \
    build-essential \
    libssl-dev \
    libgmp-dev \
    libpopt-dev \
    libcap-dev \
    libcurl4-openssl-dev \
    libsystemd-dev \
    libsqlite3-dev \
    sqlite3 \
    bison \
    flex \
    gawk \
    libmodbus5 \
    python3 \
    python3-pip \
    python3-venv \
    python3-dev \
    systemd \
    systemd-sysv \
    sysvinit-utils \
    iproute2 \
    iptables \
    openssh-server \
    ipset \
    sudo \
    supervisor \
    curl \
    rsyslog \
    mc \
    nano \
    iperf3 \
    wget 

# Configure gelf resyslog
COPY  gelf.conf /etc/rsyslog.d/30-gelf.conf



RUN mkdir /var/run/sshd && \
    echo "PermitRootLogin yes" >> /etc/ssh/sshd_config && \
    echo "PasswordAuthentication yes" >> /etc/ssh/sshd_config


RUN useradd -m -s /bin/bash gnet && \
    echo "gnet:Frdfkfyu2023!" | chpasswd && \
    mkdir -p /home/gnet/.ssh && \
    chmod 701 /home/gnet/.ssh && \
    usermod -aG sudo gnet && \
    echo "gnet ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers


COPY id_rsa.pub /home/gnet/.ssh/authorized_keys
RUN chmod 600 /home/gnet/.ssh/authorized_keys && \
    chown -R gnet:gnet /home/gnet/.ssh

# Установка StrongSwan
WORKDIR /home/gnet
RUN wget https://download.strongswan.org/strongswan-6.0.0.tar.bz2 && \
    tar -xvf strongswan-6.0.0.tar.bz2 && \
    cd strongswan-6.0.0 && \
    ./configure --prefix=/usr --sysconfdir=/etc --enable-stroke && \
    make && \
    make install


RUN wget https://repo.zabbix.com/zabbix/7.0/raspbian/pool/main/z/zabbix/zabbix-agent_7.0.8-1%2Bdebian12_arm64.deb && \
    dpkg -i ./zabbix-agent_7.0.8-1+debian12_arm64.deb


COPY zabbix_agent.conf /etc/zabbix/zabbix_agentd.conf
COPY ipsec.* /etc/
COPY supervisord.conf /etc/supervisor/supervisord.conf
COPY set-client-id.sh /usr/local/bin/set-client-id.sh
COPY strongswan.service /etc/systemd/system/strongswan.service
RUN chmod +x /usr/local/bin/set-client-id.sh

RUN systemctl enable zabbix-agent
RUN systemctl enable iperf3
RUN systemctl enable ssh
RUN systemctl enable strongswan-starter

EXPOSE 4500/udp 500/udp 22 10050 10051 5002

ENTRYPOINT [ "/bin/bash", "-c", "/usr/local/bin/set-client-id.sh" ]
CMD ["/usr/sbin/supervisord", "-c", "/etc/supervisor/supervisord.conf"]
