name: CI Workflow

on:
    push:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest, self-hosted

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Notify start of CI workflow
              run: |
                curl -s -X POST https://api.telegram.org/bot$TELEGRAM_BOT/sendMessage \
                    -d chat_id=$TELEGRAM_CHAT_ID \
                    -d text="CI workflow started for branch: $GITHUB_REF"

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v1

            - name: Login to Docker Hub
              uses: docker/login-action@v3
              with:
                  username: ${{ secrets.DOCKER_USERNAME }}
                  password: ${{ secrets.DOCKER_PASSWORD }}

            - name: Build and push Docker image
              uses: docker/build-push-action@v6
              with:
                  context: tests/client
                  push: true
                  platforms: linux/amd64,linux/arm64,linux/arm/v7
                  tags: akhaladze/ipsec-client:latest

            - name: Notify successful build and push
              run: |
                curl -s -X POST https://api.telegram.org/bot$TELEGRAM_BOT/sendMessage \
                    -d chat_id=$TELEGRAM_CHAT_ID \
                    -d text="Successfully built and pushed Docker image for branch: $GITHUB_REF"
            
            # Trigger webhook on Portainer
            - name: Trigger webhook
              run: |
                curl -X POST -H "Content-Type: application/json" ${{ vars.PORTAINER_WEBHOOK_URL_MBIT }} -d '{"message": "CI workflow completed successfully"}'
            
            # Telegram: On success
            - name: Notify success
              if: success()
              run: |
                curl -X POST https://api.telegram.org/bot${{ secrets.TELEGRAM_TOKEN }}/sendMessage \
                -d chat_id=-{{ secrets.TELEGRAM_CHAT_ID }} \
                -d text="Rep:backend(main),Action:build:ok"